services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --requirepass bundemais
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

volumes:
  redis:
    driver: local
